import{S as v,i}from"./assets/vendor-5ObWk2rO.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function l(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const m=15;async function y(r,o){throw new Error("Pixabay API key is missing. Set VITE_PIXABAY_KEY in .env file.")}const g=document.querySelector(".gallery"),h=document.querySelector(".loader"),p=document.querySelector(".load-more"),E=new v(".gallery a",{captionsData:"alt",captionDelay:250});function L(r){const o=r.map(({webformatURL:n,largeImageURL:l,tags:e,likes:t,views:a,comments:b,downloads:q})=>`
				<li class="gallery-item">
					<a class="gallery-link" href="${l}">
						<img class="gallery-image" src="${n}" alt="${e}" loading="lazy" />
					</a>
					<ul class="gallery-meta">
						<li><span>Likes</span>${t}</li>
						<li><span>Views</span>${a}</li>
						<li><span>Comments</span>${b}</li>
						<li><span>Downloads</span>${q}</li>
					</ul>
				</li>
			`).join("");g.insertAdjacentHTML("beforeend",o),E.refresh()}function B(){g.innerHTML=""}function w(){h.classList.remove("is-hidden")}function S(){h.classList.add("is-hidden")}function P(){p.classList.remove("is-hidden")}function u(){p.classList.add("is-hidden")}const f={form:document.querySelector(".search-form"),loadMoreBtn:document.querySelector(".load-more")};let d="",s=1,c=0;f.form.addEventListener("submit",M);f.loadMoreBtn.addEventListener("click",R);async function M(r){r.preventDefault();const o=r.currentTarget.elements.searchQuery.value.trim();if(!o){i.warning({position:"topRight",message:"Please enter a search query."});return}d=o,s=1,c=0,B(),u(),w();try{const n=await y(d,s);if(n.hits.length===0){i.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}c=n.totalHits,L(n.hits),s*m<c?P():(u(),i.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."}))}catch{i.error({position:"topRight",message:"Something went wrong. Please try again later."})}finally{S(),f.form.reset()}}async function R(){s+=1,u(),w();try{const r=await y(d,s);L(r.hits),$(),s*m<c?P():(u(),i.info({position:"topRight",message:"We're sorry, but you've reached the end of search results."}))}catch{s-=1,i.error({position:"topRight",message:"Something went wrong. Please try again later."})}finally{S()}}function $(){const r=document.querySelector(".gallery-item");if(!r)return;const o=r.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
